# ---------〖引進共用資料〗---------
source ./../conf/config.sh
# source ./conf/config.sh


# =============== [chroot前置作業部署] ===============
echo "=============== [chroot_start] ==============="

## 設定 DNS 用戶端要求名稱解析
echo "
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

## ===============【GV3-resolv.conf】===============
## Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
##     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
#nameserver 192.168.0.1
#search mwg

# ===============【使用 resolvectl 去查詢 systemd-resolved本地端建立的DNS伺服器 】===============
nameserver 127.0.0.53
nameserver 8.8.8.8
nameserver 8.8.4.4
options edns0 trust-ad" > /etc/resolv.conf

# 掛載系統
# chroot後的環境 proc、sys、/dev/pts 都是空的，故為了讓某些程式程序能夠順利執行(包括安裝某些套件、網路)，就需要事先掛載 proc、sysfs、devpts。
# 可參照 The Linux Programming Interface 這本書
# mount -t proc none /proc
# mount -t sysfs none /sys
# mount -t devpts none /dev/pts

# 掛載主系統所需目錄
echo "掛載主系統的 /proc, /sys, /dev/pts..."
mount -t proc none /proc || echo "/proc 已掛載或不存在"
mount -t sysfs none /sys || echo "/sys 已掛載或不存在"
mount -t devpts none /dev/pts || echo "/dev/pts 已掛載或不存在"



